id: I669674FF
legacy_id: P003166
ocr_import_info:
  bdrc_scan_id: W1KG12027
  source: bdrc
  ocr_info:
    timestamp: '2020-03-28T20:48:38'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T03:14:39.825911+00:00'
last_modified: 2022-08-31 11:15:03.734735
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG12027
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG12027
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སྡོམ་པ་གསུམ་གྱི་རབ་ཏུ་དབྱེ་བའི་རྣམ་བཤད་དང་སྤྱི་དོན་དང་ཁ་སྐོང་བཅས།
  author: ས་སྐྱ་ཡོངས་འཛིན་ངག་དབང་ཆོས་གྲགས།
statistics:
  ocr_word_mean_confidence_index: 0.6461906297434081
  ocr_word_median_confidence_index: 0.699999988079071
quality: null
bases:
  I1KG12039:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG12039
      total_pages: 730
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG12039.txt
    statistics:
      ocr_word_median_confidence_index: 0.699999988079071
      ocr_word_mean_confidence_index: 0.6461906297434081
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
